version: 1
formatters:
  simple:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  pystorz.mgen.loader:
    level: INFO
    handlers: [console]
    propagate: no
  pystorz.mgen.builder:
    level: INFO
    handlers: [console]
    propagate: no
  pystorz.sql.store:
    level: DEBUG
    handlers: [console]
    propagate: no
  test.store:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
